---
# tasks file for froxlorInstaller

- import_tasks: 'roles/system/tasks/load-vars.yaml'

- import_tasks: 'roles/system/tasks/manage-software-installations.yaml'
  vars:
    packages:
      - package_list: "{{ nss_packages|default([]) }}"
        package_status: "{{ true }}"

# Add libnss-extrausers setup instructions
- name: Run tasks to setup extrausers
  include_tasks: "libnss-extrausers.yaml"
  when: ansible_os_family == "Debian"

# Add libnss-mysql setup instructions
- name: Run tasks to setup libnss mysql
  include_tasks: "libnss-mysql.yaml"
  when: (ansible_os_family == "RedHat") or (ansible_os_family == "FreeBSD")