---
# Execute tasks for Debian

#
# Common port
#
- name: Enable required ports in ufw
  community.general.ufw:
    port: "{{ item }}"
    rule: allow
  loop:
    - ftp
    - ssh
    - http
    - https
    - smtp
    - smtps
    - submission
    - submissions
    - pop3
    - pop3s
    - imap
    - imap
    - imaps
    - dhcpv6-client
#    ignore_erros: yes
#   register: firewalld_enable_services
  notify: start ufw
# - name: Enable required ports in firewalld
#   community.general.ufw:
#     port: "{{ item }}"
#     permanent: yes
#     immediate: yes
#     state: enabled
#   when: firewalld_enable_services.failed
#   loop:
#     - 21/tcp # FTP
#     - 22/tcp # SSH
#     - 80/tcp # HTTP
#     - 443/tcp # HTTPS
#     - 25/tcp # SMTP
#     - 465/tcp # SMTPS
#     - 587/tcp # Submission
#     - 110/tcp # POP3
#     - 995/tcp # POP3S
#     - 143/tcp # IMAP
#     - 993/tcp # IMAPS
#     - 68/udp # DHCP
#     - 546/udp # DHCPv6
#     - 647/udp # DHCP-failover

#
# DNS port
#
- name: "{{ froxlor_settings.dnsenabled | ternary('Enable', 'Disabled', 'Disable') }} DNS traffic in ufw"
  community.general.ufw:
    port: "{{ item.portnr }}"
    proto: "{{ item.proto }}"
    rule: "{{ froxlor_settings.dnsenabled | ternary('allow', 'deny', 'deny') }}"
  loop:
#    - dns
#    - dns-over-tls
    - {"portnr": "53", "proto": "tcp"} # DNS
    - {"portnr": "53", "proto": "udp"} # DNS
    - {"portnr": "853", "proto": "tcp"} # DNS-DoT
    - {"portnr": "853", "proto": "udp"} # DNS-DoT
  notify: start ufw

#
# NTP Port
#
- name: Check if ntp is enabled
  shell:
    cmd: "timedatectl status | grep -o 'NTP.*$'"
  register: ntp_status
- name: "{{ ('active' in ntp_status.stdout) | ternary('Enable', 'Disabled', 'Disable') }} NTP traffic in firewalld"
  community.general.ufw:
    port: "{{ item }}"
    rule: "{{ ('active' in ntp_status.stdout) | ternary('allow', 'deny', 'deny') }}"
  loop:
    - ntp
#    - 123/tcp # NTP
#    - 123/udp # NTP
#    - 853/tcp # NTPS
#    - 853/udp # NTPS
  notify: start ufw

- name: Allow outgoing by default and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
    direction: outgoing
  notify: start ufw

- name: Allow routed/forwarded by default and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
    direction: routed
  notify: start ufw

- name: Deny incoming by default and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
  notify: start ufw