---
# handlers file for froxlorInstaller
- name: restart cron
  service:
    name: "{{ 'crond' if 'RedHat' in ansible_os_family else 'cron' }}"
    state: restarted
    enabled: yes
- name: update dnf cache
  dnf:
    update_cache: yes
