---
# handlers file for froxlorInstaller
- name: reload cron
  service:
    name: "{{ 'cron' if 'Debian' in ansible_os_family else 'crond' }}"
    state: reloaded
    enabled: yes
  when: ('Debian' not in ansible_os_family)
