---
# handlers file for froxlorInstaller
- name: restart apache2
  service:
    name: "{{ 'apache24' if ansible_os_family == 'FreeBSD' else 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: restarted
    enabled: yes
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
- name: restart php-fpm
  service:
    name: "php{{ php_version if ansible_os_family == 'Debian' }}-fpm"
    state: restarted
    enabled: yes